### ISSUE TITLE
AttributeError: 'str' object has no attribute 'search' in `load_module`

### ISSUE THREAD

**Issue by duelle** [kieker-monitoring/kieker-lang-pack-python#15]
Only on few occasions, the following line
https://github.com/kieker-monitoring/kieker-lang-pack-python/blob/4c6c5c17349040d0ee56bafd7b09c0907bc3ac00/kieker/tools/importhook.py#L31
reports an `AttributeError: 'str' object has no attribute 'search'`, leading to an exception, despite the fact that in all cases it is executed, the value of `param` is a string despite no `search` method existing for strings.

**Comment by duelle** [comment]
```
Traceback (most recent call last):
  File "/my/repository/main.py", line 13, in <module>
    import datetime
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/my/repository/venv/lib/python3.10/site-packages/tools/importhook.py", line 29, in load_module
    importlib.import_module(fullname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/datetime.py", line 2506, in <module>
    from _datetime import *
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/my/repository/venv/lib/python3.10/site-packages/tools/importhook.py", line 31, in load_module
    if self.param.search(fullname) is not None :
AttributeError: 'str' object has no attribute 'search'

```

**Comment by duelle** [comment]
> Only on few occasions, the following line
> 
> https://github.com/kieker-monitoring/kieker-lang-pack-python/blob/4c6c5c17349040d0ee56bafd7b09c0907bc3ac00/kieker/tools/importhook.py#L31
> 
> reports an `AttributeError: 'str' object has no attribute 'search'`, leading to an exception, despite the fact that in all cases it is executed, the value of `param` is a string despite no `search` method existing for strings.

Replacing the said line with:
```
if fullname in self.param:
```

does not trigger the error message anymore. I'm not 100% sure whether it does exactly the same as you intended though.

**Comment by duelle** [comment]
> > Only on few occasions, the following line
> > https://github.com/kieker-monitoring/kieker-lang-pack-python/blob/4c6c5c17349040d0ee56bafd7b09c0907bc3ac00/kieker/tools/importhook.py#L31
> > 
> > reports an `AttributeError: 'str' object has no attribute 'search'`, leading to an exception, despite the fact that in all cases it is executed, the value of `param` is a string despite no `search` method existing for strings.
> 
> Replacing the said line with:
> 
> ```
> if fullname in self.param:
> ```
> 
> does not trigger the error message anymore. I'm not 100% sure whether it does exactly the same as you intended though.

That seemed not to have worked as then (supposedly) nothing was instrumented.
Replacing the line with `if self.param in fullname:` fixed the issue for me and the intended modules were instrumented as far as I can tell by now.

**Comment by silvergl** [comment]
` self.param ` is not supposed to be a string object. It is a [regex object](https://docs.python.org/3/library/re.html) which should be matched with  `fullname` (module name).
Edit: I think it would be clever to add some type hints in the constructors.
